### ISSUE TITLE
Create TheGraph (or SpaceAndTime?) Data Structures needed

### ISSUE THREAD

**Issue by CarlosAlegreUr** [CarlosAlegreUr/Constellation-ChainlinkHackathon-2023#21]
Research if Space And Time is better for reading or indexing logs data from blockchain to use in front-end.

If so use it if not use TheGraph and create the graphs for the project.

**Comment by Ethanol48** [comment]
Me da que va a ser mejor The Graph, puedes crear custom squemas que hagas operaciones especiales para tener más datos.

Es más flexible, no creo que puedas hacer eso con Space and Time, solo indexan datos generales en la blockchain

**Comment by CarlosAlegreUr** [comment]
> ###
> **[Ethanol48](/Ethanol48) ** commented [Nov 18, 2023](#issuecomment-1817529929)

Okay pues a darle a eso. A tope :D

**Comment by Ethanol48** [comment]
We will use the Graph to extract the data from the battles and NFT metadata
